name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: codeberg-tiny
    steps:
      - uses: https://codeberg.org/actions/checkout@v4
      - uses: https://codeberg.org/actions/setup-node@v4
        with:
          node-version: 20
      - run: bun run build
      - uses: https://codeberg.org/git-pages/action@v2
        with:
          site: "https://frome.codeberg.page"
          token: ${{ forge.token }}
          source: dist/
